#!/usr/bin/env python3
"""check_skills_tree.py - prove skills/ still matches plugins/*/skills/.

Regenerates the tree into a temporary directory and compares it byte for
byte against the committed one, then asserts the invariants from ADR 0162 and
the spec. It REPORTS and never writes to skills/ - a person (or CI) reads the
findings and runs generate_skills_tree.py to repair them.

Usage:
  python3 scripts/check_skills_tree.py [--repo PATH]

Exit codes: 0 clean, 1 findings, 2 cannot run.
"""
import argparse
import collections
import io
import os
import shutil
import sys
import tempfile

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import generate_skills_tree as g


def _files_under(root):
    """Every file under root, as {posix relative path: bytes}."""
    out = {}
    for base, _dirs, files in os.walk(root):
        for name in sorted(files):
            path = os.path.join(base, name)
            rel = os.path.relpath(path, root).replace(os.sep, "/")
            with open(path, "rb") as f:
                out[rel] = f.read().replace(b"\r\n", b"\n")
    return out


def check(repo):
    """Return a list of findings. Empty means clean."""
    findings = []

    names = [s.name for s in g.discover_skills(repo)]
    for name, count in sorted(collections.Counter(names).items()):
        if count > 1:
            findings.append(
                "name '%s' is declared twice - the CLI keeps one and drops "
                "the rest (ADR 0156)" % name)

    committed_root = os.path.join(repo, g.TREE_DIRNAME)
    temp_root = tempfile.mkdtemp(prefix="skillstree-check-")
    try:
        g.build(repo, temp_root)
        expected = _files_under(temp_root)
        actual = _files_under(committed_root) if os.path.isdir(committed_root) else {}

        for rel in sorted(set(expected) - set(actual)):
            findings.append("missing from skills/: %s" % rel)
        for rel in sorted(set(actual) - set(expected)):
            findings.append("not generated by the sources: skills/%s" % rel)
        for rel in sorted(set(expected) & set(actual)):
            if expected[rel] != actual[rel]:
                findings.append(
                    "differs from what the sources generate: skills/%s" % rel)
    finally:
        shutil.rmtree(temp_root, ignore_errors=True)

    if os.path.isdir(committed_root):
        for rel, data in sorted(_files_under(committed_root).items()):
            # Only a .md file is reference-rewritten, and only a token followed by
            # a real path is a reference at all. A ${CLAUDE_PLUGIN_ROOT} inside a
            # .cs comment, or the documented prose form ${CLAUDE_PLUGIN_ROOT}/...
            # which names nothing, are both legitimate survivors (ADR 0164, and
            # the ruling recorded against Task 5).
            if not rel.endswith(".md"):
                continue
            for named in g.REF_RE.findall(data.decode("utf-8", "replace")):
                findings.append(
                    "skills/%s still names ${CLAUDE_PLUGIN_ROOT}/%s - that "
                    "expands to nothing outside a plugin install" % (rel, named))
        for rel, data in sorted(_files_under(committed_root).items()):
            if not rel.endswith(".md"):
                continue
            skill_dir = rel.split("/")[0]
            for named in g.SKILL_DIR_REF_RE.findall(data.decode("utf-8", "replace")):
                target = os.path.join(committed_root, skill_dir,
                                      named.replace("/", os.sep))
                if not os.path.isfile(target):
                    findings.append(
                        "skills/%s names %s, which is not in that skill "
                        "directory - the CLI copies nothing else" % (rel, named))

        for entry in sorted(os.listdir(committed_root)):
            md = os.path.join(committed_root, entry, "SKILL.md")
            if not os.path.isfile(md):
                continue
            declared = g.frontmatter_name(g.read_text(md))
            if declared != entry:
                findings.append(
                    "skills/%s declares name '%s' - the CLI installs by the "
                    "frontmatter name, so the two must match (ADR 0162)"
                    % (entry, declared))
    return findings


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo", default=".")
    args = parser.parse_args(argv)
    if not os.path.isdir(os.path.join(args.repo, g.PLUGINS_DIRNAME)):
        sys.stderr.write("cannot run: no %s/ under %s\n"
                         % (g.PLUGINS_DIRNAME, args.repo))
        return 2
    findings = check(args.repo)
    for f in findings:
        print("FINDING  %s" % f)
    if findings:
        print("\n%d finding(s). Repair with: "
              "python3 scripts/generate_skills_tree.py" % len(findings))
        return 1
    print("skills/ matches plugins/*/skills/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
